export enum ACTION_TYPES  { 
    NUMBER_OF_TRANSFER = "NUMBER_OF_TRANSFER",
    SELECT_ALL_NUMBERS = "SELECT_ALL_NUMBERS",
    GET_ALL_API_DATA = "GET_ALL_API_DATA",
    GET_DATA_REQUESTED = "GET_DATA_REQUESTED",
    GET_DATA_DONE = "GET_DATA_DONE",
    GET_DATA_FAILED = "GET_DATA_FAILED"
}

